server:
  port: ${PORT:0}

spring:
  application:
    name: department

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: ALWAYS
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true